services:
  mongodb:
    image: mongo:4.4
    container_name: event_mongo
    restart: unless-stopped
    env_file:
      - ./controller/.env
    ports:
      - 2717:27017

  redis:
    image: redis:latest
    container_name: event_redis
    restart: unless-stopped
    env_file:
      - ./controller/.env
    ports:
      - 6378:6379

  # client:
  #   image: eventauth:1.1
  #   container_name: event_client
  #   restart: unless-stopped
  #   env_file:
  #     - ./controller/.env
  #   depends_on:
  #     - mongodb
  #     - redis
  #   ports:
  #     - 8081:8081
