package api

const (
	HTTP_ERROR_CODE_ADD_FAILED    = 701
	HTTP_ERROR_CODE_READ_FAILED   = 702
	HTTP_ERROR_CODE_UPDATE_FAILED = 703
	HTTP_ERROR_CODE_DELETE_FAILED = 704

	DATATABLE_QUERY_OUTPUT           = "output"
	DATATABLE_QUERY_OUTPUT_DATATABLE = "datatable"
)
